on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
  
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '9.0.x'
          
      - name: Restore dependencies
        run: dotnet restore ParserComb/ParserComb.fsproj

      - name: Build project
        run: dotnet build ./ParserComb

      - name: Set DOTNET_ROLL_FORWARD
        run: echo "DOTNET_ROLL_FORWARD=latestMajor" >> $GITHUB_ENV
      - name: Lint
        run: |
          dotnet tool install -g dotnet-fsharplint
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          dotnet fsharplint lint ./ParserComb

      - name: Formatter
        run: |
          dotnet tool install -g fantomas-tool
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          fantomas ./ParserComb/*.fs 
    
      
        
      - name: Run project
        run: dotnet run --project ./ParserComb


      - name: Tests
        run: |
            
            dotnet build ./ParserComb
            dotnet test ./ParserComb.Tests
